### ISSUE TITLE
Инструкция по применению

### ISSUE THREAD

**Issue by reatailret** [liquetsoft/fias-elastic#43]
Здравствуйте.
Напишите, пожалуйста, краткое руководство по применению этого расширения. Сколько памяти нужно для эластика ,что бы фиас загрузить; пару строк кода поиска по адресу.
Спасибо за работу.

**Comment by marvin255** [comment]
Здравствуйте. 
К сожалению, в данный момент библиотека не готова для открытого использования. Мы постоянно и достаточно серьезно меняем ее API. Как только найдем нужную форму - обязательно опишем в документации.
